version: '3.2'

services:
  server:
    build: ./server
    depends_on:
      - mongo
    volumes:
      - ./server/app:/app
    ports:
      - 80:80
  
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
  
  judger:
    build: ./judger
    command: python3 script.py
    volumes:
      - ./judger/app:/app